//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exo9
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stagiaires
    {
        internal int NumOsia { get; set; }
        internal string NomStagiaire { get; set; }
        internal string PrenomStagiaire { get; set; }
        internal string rueStagiaire { get; set; }
        internal string VilleStagiaire { get; set; }
        internal string CodePostalStagiaire { get; set; }
        internal Nullable<int> NbreNotes { get; set; }
        internal Nullable<decimal> PointsNotes { get; set; }
    
        public virtual Sections Sections { get; set; }
    }
}
