//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exo9
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sections
    {
        public Sections()
        {
            this.Stagiaires = new HashSet<Stagiaires>();
        }
    
        internal string Idsection { get; set; }
        public string NomSection { get; set; }
        internal Nullable<System.DateTime> DateDebut { get; set; }
        internal System.DateTime DateFin { get; set; }
    
        public virtual ICollection<Stagiaires> Stagiaires { get; set; }
    }
}
