//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exo9.FormationService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MSection", Namespace="http://schemas.datacontract.org/2004/07/Exo9")]
    [System.SerializableAttribute()]
    public partial class MSection : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeSectionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DebutFormationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FinFormationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomSectionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodeSection {
            get {
                return this.CodeSectionField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeSectionField, value) != true)) {
                    this.CodeSectionField = value;
                    this.RaisePropertyChanged("CodeSection");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DebutFormation {
            get {
                return this.DebutFormationField;
            }
            set {
                if ((this.DebutFormationField.Equals(value) != true)) {
                    this.DebutFormationField = value;
                    this.RaisePropertyChanged("DebutFormation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FinFormation {
            get {
                return this.FinFormationField;
            }
            set {
                if ((this.FinFormationField.Equals(value) != true)) {
                    this.FinFormationField = value;
                    this.RaisePropertyChanged("FinFormation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NomSection {
            get {
                return this.NomSectionField;
            }
            set {
                if ((object.ReferenceEquals(this.NomSectionField, value) != true)) {
                    this.NomSectionField = value;
                    this.RaisePropertyChanged("NomSection");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MStagiaire", Namespace="http://schemas.datacontract.org/2004/07/Exo9")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Exo9.FormationService.MStagiaireDE))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Exo9.FormationService.MStagiaireCIF))]
    public partial class MStagiaire : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodePostalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> NbreNotesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumOsiaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double PointsNotesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrenomField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VilleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodePostal {
            get {
                return this.CodePostalField;
            }
            set {
                if ((object.ReferenceEquals(this.CodePostalField, value) != true)) {
                    this.CodePostalField = value;
                    this.RaisePropertyChanged("CodePostal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> NbreNotes {
            get {
                return this.NbreNotesField;
            }
            set {
                if ((this.NbreNotesField.Equals(value) != true)) {
                    this.NbreNotesField = value;
                    this.RaisePropertyChanged("NbreNotes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nom {
            get {
                return this.NomField;
            }
            set {
                if ((object.ReferenceEquals(this.NomField, value) != true)) {
                    this.NomField = value;
                    this.RaisePropertyChanged("Nom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumOsia {
            get {
                return this.NumOsiaField;
            }
            set {
                if ((this.NumOsiaField.Equals(value) != true)) {
                    this.NumOsiaField = value;
                    this.RaisePropertyChanged("NumOsia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double PointsNotes {
            get {
                return this.PointsNotesField;
            }
            set {
                if ((this.PointsNotesField.Equals(value) != true)) {
                    this.PointsNotesField = value;
                    this.RaisePropertyChanged("PointsNotes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Prenom {
            get {
                return this.PrenomField;
            }
            set {
                if ((object.ReferenceEquals(this.PrenomField, value) != true)) {
                    this.PrenomField = value;
                    this.RaisePropertyChanged("Prenom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Rue {
            get {
                return this.RueField;
            }
            set {
                if ((object.ReferenceEquals(this.RueField, value) != true)) {
                    this.RueField = value;
                    this.RaisePropertyChanged("Rue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ville {
            get {
                return this.VilleField;
            }
            set {
                if ((object.ReferenceEquals(this.VilleField, value) != true)) {
                    this.VilleField = value;
                    this.RaisePropertyChanged("Ville");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MStagiaireDE", Namespace="http://schemas.datacontract.org/2004/07/Exo9")]
    [System.SerializableAttribute()]
    public partial class MStagiaireDE : Exo9.FormationService.MStagiaire {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool RemuAfpaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool RemuAfpa {
            get {
                return this.RemuAfpaField;
            }
            set {
                if ((this.RemuAfpaField.Equals(value) != true)) {
                    this.RemuAfpaField = value;
                    this.RaisePropertyChanged("RemuAfpa");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MStagiaireCIF", Namespace="http://schemas.datacontract.org/2004/07/Exo9")]
    [System.SerializableAttribute()]
    public partial class MStagiaireCIF : Exo9.FormationService.MStagiaire {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FongecifField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeCifField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Fongecif {
            get {
                return this.FongecifField;
            }
            set {
                if ((object.ReferenceEquals(this.FongecifField, value) != true)) {
                    this.FongecifField = value;
                    this.RaisePropertyChanged("Fongecif");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TypeCif {
            get {
                return this.TypeCifField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeCifField, value) != true)) {
                    this.TypeCifField = value;
                    this.RaisePropertyChanged("TypeCif");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FormationService.IServiceStagiaire")]
    public interface IServiceStagiaire {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceStagiaire/GetSection", ReplyAction="http://tempuri.org/IServiceStagiaire/GetSectionResponse")]
        Exo9.FormationService.MSection GetSection(string codeSection);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceStagiaire/GetSection", ReplyAction="http://tempuri.org/IServiceStagiaire/GetSectionResponse")]
        System.Threading.Tasks.Task<Exo9.FormationService.MSection> GetSectionAsync(string codeSection);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceStagiaire/GetStagiairesSection", ReplyAction="http://tempuri.org/IServiceStagiaire/GetStagiairesSectionResponse")]
        Exo9.FormationService.MStagiaire[] GetStagiairesSection(string codeSection);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceStagiaire/GetStagiairesSection", ReplyAction="http://tempuri.org/IServiceStagiaire/GetStagiairesSectionResponse")]
        System.Threading.Tasks.Task<Exo9.FormationService.MStagiaire[]> GetStagiairesSectionAsync(string codeSection);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceStagiaire/AddStagiaire", ReplyAction="http://tempuri.org/IServiceStagiaire/AddStagiaireResponse")]
        string AddStagiaire(Exo9.FormationService.MStagiaire newStagiaire, Exo9.FormationService.MSection laSection);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceStagiaire/AddStagiaire", ReplyAction="http://tempuri.org/IServiceStagiaire/AddStagiaireResponse")]
        System.Threading.Tasks.Task<string> AddStagiaireAsync(Exo9.FormationService.MStagiaire newStagiaire, Exo9.FormationService.MSection laSection);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceStagiaire/UpdateStagiaire", ReplyAction="http://tempuri.org/IServiceStagiaire/UpdateStagiaireResponse")]
        string UpdateStagiaire(Exo9.FormationService.MStagiaire leStagiaire);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceStagiaire/UpdateStagiaire", ReplyAction="http://tempuri.org/IServiceStagiaire/UpdateStagiaireResponse")]
        System.Threading.Tasks.Task<string> UpdateStagiaireAsync(Exo9.FormationService.MStagiaire leStagiaire);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceStagiaire/DeleteStagiaire", ReplyAction="http://tempuri.org/IServiceStagiaire/DeleteStagiaireResponse")]
        bool DeleteStagiaire(int laCleStagiaire);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceStagiaire/DeleteStagiaire", ReplyAction="http://tempuri.org/IServiceStagiaire/DeleteStagiaireResponse")]
        System.Threading.Tasks.Task<bool> DeleteStagiaireAsync(int laCleStagiaire);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceStagiaireChannel : Exo9.FormationService.IServiceStagiaire, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceStagiaireClient : System.ServiceModel.ClientBase<Exo9.FormationService.IServiceStagiaire>, Exo9.FormationService.IServiceStagiaire {
        
        public ServiceStagiaireClient() {
        }
        
        public ServiceStagiaireClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceStagiaireClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceStagiaireClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceStagiaireClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Exo9.FormationService.MSection GetSection(string codeSection) {
            return base.Channel.GetSection(codeSection);
        }
        
        public System.Threading.Tasks.Task<Exo9.FormationService.MSection> GetSectionAsync(string codeSection) {
            return base.Channel.GetSectionAsync(codeSection);
        }
        
        public Exo9.FormationService.MStagiaire[] GetStagiairesSection(string codeSection) {
            return base.Channel.GetStagiairesSection(codeSection);
        }
        
        public System.Threading.Tasks.Task<Exo9.FormationService.MStagiaire[]> GetStagiairesSectionAsync(string codeSection) {
            return base.Channel.GetStagiairesSectionAsync(codeSection);
        }
        
        public string AddStagiaire(Exo9.FormationService.MStagiaire newStagiaire, Exo9.FormationService.MSection laSection) {
            return base.Channel.AddStagiaire(newStagiaire, laSection);
        }
        
        public System.Threading.Tasks.Task<string> AddStagiaireAsync(Exo9.FormationService.MStagiaire newStagiaire, Exo9.FormationService.MSection laSection) {
            return base.Channel.AddStagiaireAsync(newStagiaire, laSection);
        }
        
        public string UpdateStagiaire(Exo9.FormationService.MStagiaire leStagiaire) {
            return base.Channel.UpdateStagiaire(leStagiaire);
        }
        
        public System.Threading.Tasks.Task<string> UpdateStagiaireAsync(Exo9.FormationService.MStagiaire leStagiaire) {
            return base.Channel.UpdateStagiaireAsync(leStagiaire);
        }
        
        public bool DeleteStagiaire(int laCleStagiaire) {
            return base.Channel.DeleteStagiaire(laCleStagiaire);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteStagiaireAsync(int laCleStagiaire) {
            return base.Channel.DeleteStagiaireAsync(laCleStagiaire);
        }
    }
}
